# 用于测试github action yml 语法

name: github_action_yml_test

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build_openwrt:

    name: github action yml test

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: zzblydia/openwrt
          ref: openwrt-21.02

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git branch -a
          git log -n 1
          df -h

      - name: Update feeds
        run: |
          echo "src-git openclash https://github.com/zzblydia/OpenClash.git" >> feeds.conf.default
          echo "src-git helloworld https://github.com/zzblydia/helloworld.git" >> feeds.conf.default

          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        #run: make defconfig
        run:  |
          cp x86_64.config.buildinfo .config  # Write changes to .config
          make defconfig                      # Expand to full config
