# 用于测试github action yml 语法
# 1.测试代码checkout功能(ref可以是branch, tag or SHA)
# 2.测试if条件的作用范围(if在job里有效/if在steps里有效/if在run里无效)
# 3.测试不同job的顺序执行(默认不同job是并行, 顺序执行需要指定need)
# 4.run:后跟|符号表示一个多行字符串(Literal Block Scalar).它用于在 run 步骤中指定需要执行的多行命令. 多个命令间用空格分开时空行不用首行缩进.

name: github_action_yml_test

on:
  workflow_dispatch:
    inputs:
      compilingMode:
        description: 'compile mode'
        required: true
        default: 'debug'
        type: choice
        options:
        - download
        - debug
        - release
  release:
    types: [published]

jobs:

  job_01:
    name: job_01
    if: github.event.repository.owner.id == github.event.sender.id # 有效

    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v2
        with:
          repository: openwrt/openwrt
          ref: openwrt-23.05

      - name: code check and space check
        run: |
          git branch -a
          git log -n 1
          df -h

      - name: env check
        run: |
          echo ${{ inputs.compilingMode }}

      - name: test if 01
        if: inputs.compilingMode == 'debug' # 有效
        run: |
          echo "test if 01 output debug"

      - name: test if 02
        if: inputs.compilingMode == 'release' # 有效
        run: |
          echo "test if 02 output release"

    # - name: test if 03
    #   run: |
    #     if: inputs.compilingMode == 'debug' # 无效, 因为这里是shell的内容, shell中找不到if:
    #     echo "test if 03 output 111"
    #     echo "test if 03 output 222"
    # 
    #     echo "test if 03 output 333"
    # 
    #     if: inputs.compilingMode == 'release'
    #     echo "test if 03 output 444"
    #     echo "test if 03 output 555"
    #     
    #     echo "test if 03 output 666"
    
      - name: test if 04
        run: |
          if [ ${{ inputs.compilingMode }} == 'release' ]; then
            echo "test if 04 output release"
          else
            echo "test if 04 output ${{ inputs.compilingMode }}"
          fi 

  job_02:
    name: job_02
    if: inputs.compilingMode == 'release'

    runs-on: ubuntu-22.04
    steps:
      - name: env check
        run: |
          echo ${{ github.workflow }}
    