# 用于测试checkout具体某次提交的代码,配合openwrt编译完成后version.buildinfo/feeds.buildinfo,完整还原某次编译
# 验证hash是不是只需要前7个字符就可以???

name: x86_64_21.02_test_checkout

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 97e730a306f355f3a0ae7678a6d18336387ac495

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git branch -a
          git log -n 1
          df -h

      - name: Update feeds
        run: |
          echo "" >feeds.conf.default
          echo "src-git packages https://github.com/zzblydia/packages.git^f550d90" >> feeds.conf.default
          echo "src-git luci https://github.com/zzblydia/luci.git^bb98774" >> feeds.conf.default
          echo "src-git routing https://git.openwrt.org/feed/routing.git^b88e322" >> feeds.conf.default
          echo "src-git telephony https://git.openwrt.org/feed/telephony.git^0183c1a" >> feeds.conf.default
          echo "src-git helloworld https://github.com/zzblydia/helloworld.git^de11186" >> feeds.conf.default
          echo "src-git openclash https://github.com/zzblydia/OpenClash.git^de32945" >> feeds.conf.default

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        #run: make defconfig
        run:  |
          cp x86_64.config.buildinfo .config  # Write changes to .config
          make defconfig                      # Expand to full config
